/**
 * 定义可以用于dispatch的所有action的类型.
 */
export default {
  ADD_TODO: 'ADD_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  FETCH_REQUEST: 'FETCH_REQUEST',
  FETCH_RESPONSE: 'FETCH_RESPONSE',
  FETCH_ERROR: 'FETCH_ERROR'
};
